
name: Update CSV from OneDrive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download CSV
        run: >
          curl -L "https://ozonesarl-my.sharepoint.com/personal/stephane_garcia_ozone-conseils_fr/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fstephane_garcia_ozone-conseils_fr%2FDocuments%2FSG%2FDocs_SG%2FBridge%2FBouffémont%2FCommunication%2FSuedois%2Finscriptions_suedois.csv" -o inscriptions_suedois.csv

      - name: Commit updates
        run: |
          git config --local user.name "AutoUpdate"
          git config --local user.email "update@example.com"
          git add inscriptions_suedois.csv
          git commit -m "Auto update from OneDrive" || echo "No changes"
          git push
